name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'    # e.g. v1.2.3 — adjust to your versioning scheme
  release:
    types: [created, published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          pip install build twine
      - run: python -m build
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
